name: Maven Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Download and Install ChromeDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin
        sudo chmod +x /usr/local/bin/chromedriver
        rm chromedriver_linux64.zip

    - name: Set system property for Chrome WebDriver
      run: echo "webdriver.chrome.driver=/usr/local/bin/chromedriver" >> $GITHUB_ENV

    - name: Install Dependencies
      run: mvn -B install

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test with Maven
      run: mvn test
