name: Maven Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Download and Install Microsoft Edge WebDriver
      run: |
        wget https://msedgedriver.azureedge.net/latest/MicrosoftEdgeDriver.zip
        unzip MicrosoftEdgeDriver.zip
        sudo mv msedgedriver /usr/local/bin
        sudo chmod +x /usr/local/bin/msedgedriver
        rm MicrosoftEdgeDriver.zip

    - name: Set system property for Edge WebDriver
      run: echo "webdriver.edge.driver=/usr/local/bin/msedgedriver" >> $GITHUB_ENV

    - name: Install Dependencies
      run: mvn -B install

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test with Maven
      run: mvn test
