name: Selenium with TestNG - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
     
    # - name: Set up Chrome
    #   uses: browser-actions/setup-chrome@latest
    # - run: chrome --version

    - name: 'BrowserStack Env Setup'
      uses: browserstack/github-actions/setup-env@master
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESSKEY }}
     
    - name: Build with Maven
      run: mvn -B clean test

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports

  download-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports